version: "2"
services:
  mongo:
    image: mongo
    container_name: survive-sports-mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - data-volume:/data/db
    network_mode: nginx-proxy

  survive-sports:
    build: .
    container_name: survive-sports
    expose:
      - 3000
    restart:
      always
    environment:
      VIRTUAL_HOST: survive-sports.com,www.survive-sports.com
      LETSENCRYPT_HOST: survive-sports.com,www.survive-sports.com
      LETSENCRYPT_EMAIL: brent.rager@gmail.com
    network_mode: nginx-proxy

volumes:
  data-volume:

networks:
  default:
    external:
      name: nginx-proxy